### PR TITLE
Added Threshold and Notification Settings for Power Meter devices

### PR DESCRIPTION
**Pull request by timlarson345**
Use Case: I have a Z-Wave outlet that reports power usage in Watts.  I need to be notified if the power usage is outside its normal threshold.  In my case, it's for a pump for a pond with fish in it.  If the pump dies, the power usage will (presumably) go down to somewhere near zero, even though the outlet will still be on and operational.  If this goes on for too long without my being aware, the fish can die.  Receiving a notification when the power usage in Watts drops below a certain threshold can help to keep my fish alive.

I've tested this for too-high, too-low, and within the threshold notifications.  I modeled it after the code for temperature  monitoring.

I tried to follow the patterns and conventions I saw, but please let me know if anything needs to be changed, and I'll be glad to update the pull request.

### CODE REVIEW

**Comment by krlaframboise** [comment]
I couldn't accept the pull request because it created a duplicate capability and it added some unused css, but I worked your changes into a new version.

**Comment by timlarson345** [comment]
@krlaframboise , thanks for updating the code to include this feature.  I'm grateful for the work you've done to put this together.  This SmartApp is a great addition to my SmartThings setup.

However, I would have appreciated it I had been given the opportunity to fix the problems in my pull request rather than having copy/paste done to check the code in outside of the pull request.  Because of the copy/paste, I don't get credit for the changes I made on the [contributor graph](https://github.com/krlaframboise/SmartThings/graphs/contributors).  If I had a chance to merge/fix my changes (or if you had fixed them in the pull request and then accepted the pull request), I would appear on the contributors graph.

Perhaps it's silly, but it is a type of gamification that encourages people to contribute to open source projects, and it makes me happy when I see myself on various open source projects.  Plus, it allows current or potential future employers to see what type of code I've written, because this code change would then show up on my GitHub account.

Thanks for considering.

**Comment by krlaframboise** [comment]
If you had added new logic I might have done that, but all you did is copy and paste blocks of my code and modify the names, values and static text.

None of the projects in my SmartThings repository are community projects and the only reason I post code to GitHub is to allow users to access it through SmartThings GItHub integration.

I'd much rather have users ask me to make changes than to submit pull requests because SmartThings has no debugging or automated testing tools so It takes me less time to make changes myself than it does to review and test changes made my others.

**Comment by timlarson345** [comment]
@krlaframboise Thanks for explaining.

In light of your comments, I would request that you add these guidelines to the project, perhaps in the form of a CONTRIBUTING document (https://github.com/blog/1184-contributing-guidelines), so that others that might be interested in helping out will know what is expected.

**Pull request closed without merging**
