### PR TITLE
Add types to variables in getLastEventThresholdMS to work around cast error

### PR DESCRIPTION
**Pull request by vl4ds**
I've been seeing some issues around type casting on this line on the platform side. Not exactly sure yet why this is causing issues since its typed as a number in the input but this change will help reduce stress on the platform.

### CODE REVIEW

**Comment by krlaframboise** [comment]
You must be using a last event threshold of at least 24 days in order for that to happen.  SmartThings only keeps events for 7 days so I'm pretty sure I originally restricted the input.  I believe I removed the restriction once I started caching the last event times, but I didn't think to test a number that high.

This is only affecting a handful of users so there's no way it's putting noticeable stress on the platform, but it does need to be fixed.

I'll make your change and give credit you in the release notes, but I won't be accepting the merge request because I have unpublished changes of my own that I planned on releasing later today anyways.

**Comment by vl4ds** [comment]
Thanks! Didn't mean to imply that the platform is hurting a lot because of it - the main concern is disk space because the ClassCastException that gets printed in our logs is the number 7 repeated a lot of times. We need more resilience on that side as well but figured this would be a good fix to put in place while we work on logging safety on our end.

**Comment by krlaframboise** [comment]
I didn't realize you were from SmartThings and thought you were a user reporting an error based on their setup.

I released your fix, but where are you seeing those errors?  

I tested every combination of settings I could think of before applying your change and it didn't generate any errors in Live Logging so the problem is not what I thought it was.

I've reviewed that segment of code and the unitMS variable is only assigned a value from functions declared as long so explicitly declaring it as long will have no effect.

The only way your change would fix a problem is if the setting lastEventThreshold is returning something other than an Integer, Long or null.  As far as I know, that shouldn't be possible because that input has the type "number".

**Comment by vl4ds** [comment]
Every now and then an installation pops up that exhibits this behavior (usually one at a time). Like I said in the first post (and how you discovered in your testing) I am struggling to understand how that happens because the input is typed as a number and wanted to put this in as a stop gap fix while I investigate how this is occurring. I'm pretty convinced that the root issue is platform related. I do appreciate that you made the change even though it should have worked as is (As far as I can tell).

**Comment by krlaframboise** [comment]
If that setting is returning something other than a number, I'm pretty sure the setting would need to be explicitly cast into a long to eliminate that cast exception so I doubt the new version solved anything.

I don't protect against problems that shouldn't be possible so there are at least 3 other sections of this SmartApp that could be throwing cast exceptions if the settings aren't returning the correct types.

I'm expecting to see a slight increase in users soon because some users don't use SmartTiles enough to make it worth paying for, but they still want to be able to occasionally view their devices from their computer.

Because of that, I'll go through the SmartApp and fix all the sections that could potentially have this problem and going forward I won't make the assumption that the settings work the way they're supposed to.

**Pull request closed without merging**
